### PR TITLE
fix: use new api for language examples

### LINKED ISSUE #13: ErrorException: Warning: file_get_contents(http://r.keymanweb.com/api/3.0/keyboards/basic_kbdes/es): failed to op...
Sentry Issue: [KEYMANWEB-COM-3](https://sentry.keyman.com/organizations/keyman/issues/2166/?referrer=github_integration)

```
ErrorException: Warning: file_get_contents(http://r.keymanweb.com/api/3.0/keyboards/basic_kbdes/es): failed to open stream: HTTP request failed! HTTP/1.1 404 Failure

  File "\renderLanguageExample.php", line 22, in renderLanguageExample
    $json = file_get_contents($string);
  File "\languageexample.php", line 43
    renderLanguageExample($keyboard, $language, $morehelp);
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #13.
Fixes KEYMANWEB-COM-3.

Language examples are now loaded from api.keyman.com/keyboard instead of from r.keymanweb.com. Also added _common/KeymanHosts.php and updated language examples to reference that instead of hardcoded url.

### CODE REVIEW

File: _include/autoload.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
+<?php
+  spl_autoload_register(function ($class_name) {
+    if(preg_match('/^Keyman\\\\Site\\\\com\\\\keymanweb\\\\(.+)/', $class_name, $matches)) {
```
Comment (mcdurdin) [inline _include/autoload.php:3]: We don't have any files there, hence the .keep file. But the infrastructure is in place for additional files later (and then we can delete the .keep file).

**Review by darcywong00 — APPROVED** [review]
lgtm
