### PR TITLE
fix: delays kmw-dependent code 'til full page load

### LINKED ISSUE #26: bug: Mobile use currently incompatible with ClipboardJS
Sentry Issue: [KEYMANWEB-COM-12](https://sentry.keyman.com/organizations/keyman/issues/2199/?referrer=github_integration)

```
Error: Invalid "target" attribute. Please use "readonly" instead of "disabled" attribute
  at ClipboardAction.set (/ajax/libs/clipboard.js/2.0.4/clipboard.js:547:31)
  at ClipboardAction.resolveOptions (/ajax/libs/clipboard.js/2.0.4/clipboard.js:356:25)
  at new ClipboardAction (/ajax/libs/clipboard.js/2.0.4/clipboard.js:338:14)
  at Clipboard.onClick (/ajax/libs/clipboard.js/2.0.4/clipboard.js:202:36)
  at HTMLDivElement.<anonymous> (/ajax/libs/clipboard.js/2.0.4/clipboard.js:184:31)
```

### LINKED ISSUE #27: ReferenceError: keyman is not defined
Sentry Issue: [KEYMANWEB-COM-60](https://sentry.keyman.com/organizations/keyman/issues/2695/?referrer=github_integration)

```
ReferenceError: keyman is not defined
  at getKeymanWeb (/cdn/deploy/js/kmwlive.663f7399d98a234f17ddc68d22c8b805.js:11:3)
  at updateSize (/cdn/deploy/js/kmwlive.663f7399d98a234f17ddc68d22c8b805.js:127:9)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #26.
Mitigates (and _may_ fix) #27.

Moves all KMW-dependent code (including the 'kmw-disabled' removal bit that fixes #26) until the window has fully loaded, meaning that _all_ script resources (like KMW) have loaded.  The old placement of the code could trigger at the 'interactive' state, and before KMW's script loaded at that... which would naturally cause null reference errors.

Note that the clipboard may not work on old iOS devices, but that limitation is due to Safari's support for the underlying command - it's only supported at and after iOS 10.  Unfortunately, the mobile layout gives no indication of failure due to use of an older iOS version.

There are a few additional spots in code that may allow #27 to continue occurring; additional work is suggested in these regards.  This PR should still mitigate things, though, and releasing the current fixes should help evaluate the scale needed for any remaining work in that direction.

### CODE REVIEW

File: cdn/dev/js/kmwlive.js [hunk 1]
```diff
@@ -241,6 +240,28 @@ $(document).ready(function() {
   window.setInterval(refreshButtons,200);  
 });
 
+// The KeymanWeb script will have loaded by this point, though initialization may be another matter.
+// Promises only started being supported in KMW 13 (keymanapp/keyman#1432), but this site supports
+// earlier versions, too, so we can't rely on their presence.
```
Comment (mcdurdin) [inline cdn/dev/js/kmwlive.js:245]: Happy for this site to support 13.0+ at this point if that makes things more elegant?

File: cdn/dev/js/kmwlive.js [hunk 2]
```diff
@@ -241,6 +240,28 @@ $(document).ready(function() {
...
+$(window).on("load", function() { 
+  // Focus on message box
+  setTimeout(function(){
+    if (!!$('.messageBox').length) {
+      getKeymanWeb().moveToElement('message');
+    }
+    // On touch devices, this is necessary (but not sufficient) for ClipboardJS compatibility.
+    // Must take affect AFTER KMW has initialized.
+    $('#message').removeAttr('disabled');
+  },1000);
```
Comment (mcdurdin) [inline cdn/dev/js/kmwlive.js:255]: Is `setTimeout` really needed here now? Would be *awesome* if we could eliminate it.

**Review by mcdurdin — APPROVED** [review]

File: cdn/dev/js/kmwlive.js (hunk 2 above)
Comment (jahorton) [reply cdn/dev/js/kmwlive.js:255]: It _would_ be.  That's the part that needs KMW 13.0.

If KMW's script is the last thing to load on the page, `keyman.init` may not have been called, meaning the touch-aliases won't have been built yet.  If we could wait on `init`'s `Promise`, we could eliminate this timeout in favor of that.

Assuming that making an init call here is safe, granted:  this function doesn't know whatever options the site may be setting elsewhere for its init.

Comment (mcdurdin) [reply cdn/dev/js/kmwlive.js:255]: So... if we make this 13.0+ then we can eliminate the timeout? Sounds good to me.

Comment (jahorton) [reply cdn/dev/js/kmwlive.js:255]: I've gone ahead and made this into #29.  That way, we get the current batch of work out, and just in case there _is_ any issue with use of init-promises, we can more easily revert just that part.
