### PR TITLE
fix: adds #message-value retrieval null-guard

### LINKED ISSUE #111: bug: button refreshing callback can trigger JS error on page refresh
This corresponds to a Sentry error report in which the `#message` element, statically defined within the main page's HTML, is `undefined` when reference.  The method directly triggering the error is only called after the page is fully loaded, with the caller being a `window.setInterval` call at the end of the `$(document).ready()` callback method.

(The `setInterval` call)
https://github.com/keymanapp/keymanweb.com/blob/81d1f6284f30797fef76b67efba549a22889d15f/cdn/dev/js/kmwlive.js#L245

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #111.

### CODE REVIEW

File: cdn/dev/js/kmwlive.js [hunk 1]
```diff
@@ -272,7 +272,14 @@ function refreshButtons() {
   var len=getKMWInputLength('message'); // returns -1 for desktop page element
 
   if(len < 0) {
-    len=$('#message').val().length;
+    // refreshButtons runs via setInterval.  It is possible for one call to persist through page reload,
+    // in which case the #message element is unavailable.
+    var message = $('#message').val();
+    if(!message) {
+      return;
```
Comment (darcywong00) [inline cdn/dev/js/kmwlive.js:279]: Does this prevent buttons from getting reset? ll 286-292

Comment (jahorton) [reply cdn/dev/js/kmwlive.js:279]: It does, though I believe this in a specific case where it would be _impossible_ to reset them.  If the `#message` element is inaccessible, the others likely are as well.

**Review by darcywong00 — APPROVED** [review]
lgtm
