### PR TITLE
fix: don't attempt to set OSK size before layout is complete

### LINKED ISSUE #57: bug: TypeError: Cannot read property 'setRect' of null
Sentry Issue: [KEYMANWEB-COM-2W](https://sentry.io/organizations/keyman/issues/2830490073/?referrer=github_integration)

```
TypeError: Cannot read property 'setRect' of null
  at updateSize (/cdn/deploy/js/kmwlive.e14967304e683013e6f633dab2d07021.js:157:23)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #57.
Fixes KEYMANWEB-COM-2W

Assumption I am making is that `keyman.osk` is not yet init, even if the script is loaded.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
@darcywong00 curious why you merged this? I was hoping for feedback from @jahorton

**Comment by darcywong00** [comment]
My bad. I was trying to merge my PR from another repo and clicked the green button on the wrong tab.

File: cdn/dev/js/kmwlive.js [hunk 1]
```diff
@@ -122,7 +122,7 @@ $(document).ready(function() {
 
     // We can't proceed any further if KMW hasn't loaded yet.
     // No point handling resizes until that's occurred.
-    if(!getKeymanWeb()) {
+    if(!getKeymanWeb() || !getKeymanWeb().osk) {
```
Comment (jahorton) [inline cdn/dev/js/kmwlive.js:125]: There's definitely not much that can be done if KeymanWeb itself hasn't loaded.

If we wanted to be a bit fancier about the case where the `keyman` global exists but the OSK hasn't been initialized, we could make this function async instead, doing something like...

```
if(!getKeymanWeb()) {
  return;
} else if(!getKeymanWeb().osk) {
  await keyman.init();
}
```

Though that might run into a noted issue with how KeymanWeb's `init` function gets called multiple times.

Alternatively... I see there is an `afterInit` function defined within this source file.  It doesn't yet call `updateSize()`, but I see no reason it couldn't if this case is something we strongly wish to handle.

**Comment by mcdurdin** [comment]
> My bad. I was trying to merge my PR from another repo and clicked the green button on the wrong tab.

No worries mate :grin:

File: cdn/dev/js/kmwlive.js (hunk 1 above)
Comment (mcdurdin) [reply cdn/dev/js/kmwlive.js:125]: It's probably less black-box-breaking to verify `keyman.initialized == 2`? However, what we have should at least be working for now.

Comment (jahorton) [reply cdn/dev/js/kmwlive.js:125]: `keyman.initialized == 1` would actually be sufficient.  Also, I don't think we ever reach `2` when embedding KMW in the apps.

Comment (mcdurdin) [reply cdn/dev/js/kmwlive.js:125]: `keyman.initialized != 0`?
